AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/{rails,rake,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 80 

Metrics/BlockLength:
  Max: 50

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor: 
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands: 
  Enabled: false
Lint/DeprecatedOpenSSLConstant: 
  Enabled: false
Lint/DuplicateElsifCondition: 
  Enabled: false
Lint/DuplicateRescueException: 
  Enabled: false
Lint/EmptyConditionalBody: 
  Enabled: false
Lint/FloatComparison: 
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/StringConcatenation:
  Enabled: false


