AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/{rails,rake,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 80 

Metrics/BlockLength:
  Max: 50

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

